DROP TABLE IF EXISTS TEAM2_ANSWERS_TBL, TEAM2_QUESTIONS_TBL, TEAM2_STUDY_LOGS_TBL, TEAM2_FIELDS_TBL, TEAM2_USERS_TBL;

CREATE TABLE TEAM2_USERS_TBL (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_ID VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    IS_DELETED TINYINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TEAM2_FIELDS_TBL (
	FIELD_ID INT AUTO_INCREMENT PRIMARY KEY,
	FIELD_NAME VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE TEAM2_STUDY_LOGS_TBL (
STUDY_LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT NOT NULL,
FIELD_ID INT NOT NULL,
STUDY_DATE DATE NOT NULL,
STUDY_NAME VARCHAR(100),
STUDY_CONTENT VARCHAR(300),
STUDY_TIME INT NOT NULL,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(USER_ID) REFERENCES TEAM2_USERS_TBL(USER_ID),
FOREIGN KEY(FIELD_ID) REFERENCES TEAM2_FIELDS_TBL(FIELD_ID)
);


CREATE TABLE TEAM2_QUESTIONS_TBL(
	QUESTION_ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	FIELD_ID INT NOT NULL,
	STUDY_NAME VARCHAR(100),
	QUESTION_TYPE VARCHAR(10) NOT NULL,
	QUESTION_TEXT VARCHAR(500) NOT NULL,
	CHOICE_A VARCHAR(100),
	CHOICE_B VARCHAR(100),
	CHOICE_C VARCHAR(100),
	CHOICE_D VARCHAR(100),
	CORRECT_ANSWER VARCHAR(100) NOT NULL,
	EXPLANATION VARCHAR(500),
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(USER_ID) REFERENCES TEAM2_USERS_TBL(USER_ID),
	FOREIGN KEY(FIELD_ID) REFERENCES TEAM2_FIELDS_TBL(FIELD_ID)
);

CREATE TABLE TEAM2_ANSWERS_TBL(
ANSWER_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT NOT NULL,
QUESTION_ID INT NOT NULL,
USER_ANSWER VARCHAR(300) NOT NULL,
IS_CORRECT TINYINT NOT NULL,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(USER_ID) REFERENCES TEAM2_USERS_TBL(USER_ID),
FOREIGN KEY(QUESTION_ID) REFERENCES TEAM2_QUESTIONS_TBL(QUESTION_ID)
);