INSERT INTO TEAM2_USERS_TBL (LOGIN_ID, PASSWORD, USER_NAME, IS_DELETED)
VALUES ('user0001', 'user0001', 'user0001', 0);

INSERT INTO TEAM2_USERS_TBL (LOGIN_ID, PASSWORD, USER_NAME, IS_DELETED)
VALUES ('user0002', 'user0002', 'user0002', 0);


INSERT INTO TEAM2_FIELDS_TBL (FIELD_NAME)
VALUES ('人間力');
INSERT INTO TEAM2_FIELDS_TBL (FIELD_NAME)
VALUES ('技術力');
INSERT INTO TEAM2_FIELDS_TBL (FIELD_NAME)
VALUES ('資格');
INSERT INTO TEAM2_FIELDS_TBL (FIELD_NAME)
VALUES ('その他');
