DROP TABLE IF EXISTS TEAM2_USERS_TBL;

CREATE TABLE TEAM2_USERS_TBL (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_ID VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    IS_DELETED TINYINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);